config/routes.rb
Rails.application.routes.draw do

  get 'photos/index'
  get 'about/index'
  get 'portfolio/index'
  get 'home/mobile'

  namespace :admin do
    get 'sessions/index'
  end
  namespace :admin do
    get 'posts/index'
    get 'posts/edit'
    get 'posts/new'
  end
  namespace :admin do
    get 'dashboard/index'
  end

  get 'archives/index'
  get 'blogs/show'
  get 'blogs/index'

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  def index
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def show
    @article="> #####ブール値の命名
>
> 真偽値を返す関数またはブール変数の名前を選択するときは、真偽が本当に意味するものが明確であることを確認してください。
>
> ここに危険な例があります：
> 	bool read_password = true;
>
> あなたがそれをどのように読んでいるか（意図していない）に応じて、2つの全く異なる解釈があります：
>
> - パスワードを読む必要があります
> - パスワードはすでに読み込まれています
>
> この場合、「読み込み」という単語を避け、need_passwordまたはuser_is_authenticatedという名前を付けてください。"
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def mobile
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
  end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  def markdown(text)
    render_options = {
        filter_html: false,
        hard_wrap: true
    }
    renderer = Redcarpet::Render::HTML.new(render_options)

    extensions = {
        autolink: true,
        fenced_code_blocks: true,
        lax_spacing: true,
        no_intra_emphasis: true,
        strikethrough: true,
        superscript: true,
        tables: true,
    }
    Redcarpet::Markdown.new(renderer, extensions).render(text).html_safe
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/views/about/index.html.erb
<h1>About#index</h1>
<p>Find me in app/views/about/index.html.erb</p>

app/views/archives/index.html.erb
<h1>Archives#index</h1>
<p>Find me in app/views/archives/index.html.erb</p>

app/views/blogs/_menu.html.erb
<aside class="menu">
  <div class="menu-label">
    <span>Vergil's blog</span>
    <p>Quick notes</p>
  </div>
  <ul class="menu-list">
    <li><%= link_to "index" do %>
        <i class="fas fa-home menu-icon"></i>
        <span>主页</span>
        <% end %></li>
    <li><%= link_to "index" do %>
        <i class="fas fa-tags menu-icon"></i>
        <span>标签</span>
      <% end %></li>
    <li><%= link_to "index" do %>
        <i class="far fa-calendar-alt menu-icon"></i>
        <span>归档</span>
      <% end %></li>
    <li><%= link_to "index" do %>
        <i class="fas fa-search menu-icon"></i>
        <span>搜索</span>
      <% end %></li>
  </ul>
</aside>

app/views/blogs/index.html.erb
<div id="blogs">
  <div class="container">
    <div class="columns">
      <div class="column is-3"><!-- 页内导航 -->
        <div class="blogs-menu">
        <%= render 'menu' %>
        </div>
      </div>

      <div class="column is-9"><!-- 内容 -->
        <div class="box" style="min-height:700px">
          <div class="content"><!-- 首页 -->
            <%# @articles.each do |article| %>
              <article>
                <header class="has-text-centered">
  <!--                <h1><%#= article.title %></h1>-->
                  <h1>title</h1>
                  <div class="tag" style="margin-bottom: 20px">tag</div>
  <!--                <div class="content"><%#= article.text %></div>-->
                </header>
                <div style="margin-bottom: 30px">
                  <%=  markdown("> #####ブール値の命名
> 真偽値を返す関数またはブール変数の名前を選択するときは、真偽が本当に意味するものが明確であることを確認してください。
> ここに危険な例があります：
> 	bool read_password = true;")%>
                </div>
                <div class="has-text-centered"><%= link_to '阅读全文', blogs_show_path, class: "button is-active" %></div>
              </article>
            <%# end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/blogs/show.html.erb
<div id="blogs">
  <div class="container">
    <div class="columns">
      <div class="column is-3"><!-- 页内导航 -->
        <div class="blogs-menu">
          <%= render 'menu' %>
        </div>
      </div>

      <div class="column is-9"><!-- 内容 -->
        <div class="box">
          <div class="content" style="padding: 5px 0px 20px"><!-- 首页 -->
            <%# @articles.each do |article| %>
            <article>
              <header class="has-text-centered">
                <!--                <h1><%#= article.title %></h1>-->
                <h1>title</h1>
                <div class="tag" style="margin-bottom: 20px">tag</div>
                <!--                <div class="content"><%#= article.text %></div>-->
              </header>
              <div style="margin-bottom: 30px">
                <div>
                  <%=  markdown("> #####ブール値の命名
>
> 真偽値を返す関数またはブール変数の名前を選択するときは、真偽が本当に意味するものが明確であることを確認してください。
>
> ここに危険な例があります：
> 	bool read_password = true;
>
> あなたがそれをどのように読んでいるか（意図していない）に応じて、2つの全く異なる解釈があります：
>
> - パスワードを読む必要があります
> - パスワードはすでに読み込まれています
>
> この場合、「読み込み」という単語を避け、need_passwordまたはuser_is_authenticatedという名前を付けてください。
>
> 一般に、is、has、canのような単語を追加すると、ブール値をより明確にすることができます。
>
> たとえば、SpaceLeft（）という名前の関数は数値を返すように聞こえます。 ブール値を返すことを意図していた場合、より良い名前はHasSpaceLeft（）です。
>
> 最後に、名前の否定された語句を避けるのが最善です。 たとえば、次の代わりに：
> 	```bool disable_ssl = false;```
>
> それを読んで（そしてよりコンパクトに）言うのがより簡単になります：
> 	```bool use_ssl = true;``` ")%>
                </div>
              </div>
            </article>
            <%# end %>
          </div>
        </div>
        <div><!-- 评论 -->
          <div class="field is-horizontal">
            <div class="field-body">
              <div class="field">
                <div class="control">
                  <textarea class="textarea" placeholder="添加你的评论..."></textarea>
                </div>
              </div>
            </div>
          </div>
          <div class="field is-horizontal">
            <div class="field-body">
              <div class="field">
                <p class="control is-expanded has-icons-left">
                  <input class="input" type="text" placeholder="名字">
                  <span class="icon is-small is-left">
                    <i class="fas fa-user"></i>
                  </span>
                </p>
              </div>
              <div class="field">
                <p class="control is-expanded has-icons-left has-icons-right">
                  <input class="input" type="email" placeholder="your@example.mail">
                  <span class="icon is-small is-left">
                    <i class="fas fa-envelope"></i>
                  </span>
                  <span class="icon is-small is-right">
                    <i class="fas fa-check"></i>
                  </span>
                </p>
              </div>
            </div>
          </div>
          <div class="field is-grouped is-grouped-right">
            <p class="control">
              <a class="button is-primary">
                提交
              </a>
            </p>
            <p class="control">
              <a class="button is-light">
                返回
              </a>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div id="home">
  <div class="container">
    <header class="hero is-large"><!-- 页头 -->
      <div class="hero-body">
        <div class="inner">
          <h1 class="title level-item has-text-centered">VERGIL's Blog</h1>
          <p class="subtitle level-item has-text-centered has-text-white">这是我制作的第一个动态网页项目，初步目标是建立起摄影，设计，博客三大板块的的发布及管理，以及评论功能。
          </p>
        </div>
        <div class="has-text-centered">
          <span class="has-text-white  arrow">
            <i class="fas fa-angle-down fa-3x"></i>
          </span>
        </div>

      </div>
    </header>

    <div><!-- 内容 -->
      <section class="hero is-bold">
        <div class="hero-body">
          <div>
            <h2 class="title">个人简介</h2>
            <div class="hr"></div>
            <p class="subtitle ">Vergil，本名严亦斌。现在日本就读首都大学东京工业设计研究院。学部主攻GPU高性能并列计算，现主攻CG动作捕捉。<br>兴趣大概有WEB，平面设计，室内设计，绘画，摄影，视频后期，游戏，料理，红酒，读书，木工等等。<br>广而不精，喜欢了解新鲜的领域。</p>
          </div>
          <div class="inner">
            <span>icon</span>
            <span>icon</span>
            <span>icon</span>
          </div>
        </div>
      </section>

      <div>
        <section >
          <div class="columns">
            <div  class="column">
              <img src="assets/pic01.jpg">
            </div>
            <div  class="column">
              <h2 class="title">影集</h2>
              <p class="subtitle">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam</p>
            </div>
          </div>
        </section>

        <section>
          <div class="columns">
            <div class="column">
              <h2 class="title">影集</h2>
              <p class="subtitle">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam</p>
            </div>
            <div class="column">
              <img src="assets/pic02.jpg">
            </div>
          </div>
        </section>

        <section>
          <div class="columns">
            <div class="column">
              <img src="assets/pic03.jpg">
            </div>
            <div class="column">
              <h2 class="title">影集</h2>
              <p class="subtitle">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam</p>
            </div>
          </div>
        </section>
      </div>

      <section class="hero is-bold">
        <div>
          <div class="hero-body">
            <h2 class="title">博客</h2>
            <div class="hr"></div>
            <p class="subtitle">由于这是属于个人介绍的主页，在思考页面逻辑的时候，我就打算将首页作为以标签为主。</p>
          </div>
          <div>
            <div class="vcard">
              <h3>WEB</h3>
              <p class="subtitle">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo</p>
            </div>
            <div class="vcard">
              <h3>CG</h3>
              <p class="subtitle">cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>

            <div class="vcard">
              <h3>料理</h3>
              <p class="subtitle">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo</p>
            </div>
            <div class="vcard">
              <h3>摄影</h3>
              <p class="subtitle">cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>

            <div class="vcard">
              <h3>读书</h3>
              <p class="subtitle"> class="subtitle"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo</p>
            </div>
            <div class="vcard">
              <h3>其他</h3>
              <p class="subtitle">cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>
          </div>

        </div>
      </section>
    </div>
  </div>
</div>

app/views/home/mobile.html.erb
<h1>Home#mobile</h1>
<p>Find me in app/views/home/mobile.html.erb</p>

app/views/photos/index.html.erb
<section class="hero is-medium is-bold">
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title is-1" style="color: #999999">Vergil's Photos</h1>
      <p class="subtitle has-text-grey-light">Quick view</p>
    </div>
  </div>
</section>

<section class="container">
  <div class="columns">
    <div class="column is-3">
      <div>
        <%= image_tag("banner") %>
      </div>
    </div>
    <div class="column is-3">
      <div>
        <%= image_tag("banner") %>
      </div>
    </div>
    <div class="column is-3">
      <div>
        <%= image_tag("banner") %>
      </div>
    </div>
    <div class="column is-3">
      <div>
        <%= image_tag("banner") %>
      </div>
    </div>
  </div>
  <div class="columns">
    <div class="column is-3">
      <div>
        <%= image_tag("banner") %>
      </div>
    </div>
    <div class="column is-3">
      <div>
        <%= image_tag("banner") %>
      </div>
    </div>
    <div class="column is-3">
      <div>
        <%= image_tag("banner") %>
      </div>
    </div>
    <div class="column is-3">
      <div>
        <%= image_tag("banner") %>
      </div>
    </div>
  </div>
  <div class="columns">
    <div class="column is-3">
      <div>
        <%= image_tag("banner") %>
      </div>
    </div>
    <div class="column is-3">
      <div>
        <%= image_tag("banner") %>
      </div>
    </div>
    <div class="column is-3">
      <div>
        <%= image_tag("banner") %>
      </div>
    </div>
    <div class="column is-3">
      <div>
        <%= image_tag("banner") %>
      </div>
    </div>
  </div>

  <div style="margin-bottom: 80px">
    <div style="float: right">
      <i class="fas fa-arrow-up"></i>
    </div>
  </div>
</section>

app/views/portfolio/index.html.erb
<section class="hero is-medium is-bold">
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title is-1" style="color: #999999">Vergil's Portfolio</h1>
      <p class="subtitle has-text-grey-light">Quick view</p>
    </div>
  </div>
</section>

<section>
  <div class="columns">
    <div class="column is-6">
      <div>
        <%= image_tag("banner") %>
      </div>
    </div>
    <div class="column is-6">
      <div>
        <%= image_tag("banner") %>
      </div>
    </div>
  </div>
  <div class="columns">
    <div class="column is-6">
      <div>
        <%= image_tag("banner") %>
      </div>
    </div>
    <div class="column is-6">
      <div>
        <%= image_tag("banner") %>
      </div>
    </div>
  </div>
  <div class="columns">
    <div class="column is-6">
      <div>
        <%= image_tag("banner") %>
      </div>
    </div>
    <div class="column is-6">
      <div>
        <%= image_tag("banner") %>
      </div>
    </div>
  </div>
  <div style="margin-bottom: 80px">
    <div style="float: right">
      <i class="fas fa-arrow-up"></i>
    </div>
  </div>
</section>