config/routes.rb
Rails.application.routes.draw do

  get 'photos/index'
  get 'about/index'
  get 'portfolio/index'
  get 'home/mobile'

  namespace :admin do
    get 'sessions/index'
  end
  namespace :admin do
    get 'posts/index'
    get 'posts/edit'
    get 'posts/new'
  end
  namespace :admin do
    get 'dashboard/index'
  end

  get 'archives/index'
  get 'blogs/show'
  get 'blogs/index'

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  def index
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def show
    @article="> #####ブール値の命名
>
> 真偽値を返す関数またはブール変数の名前を選択するときは、真偽が本当に意味するものが明確であることを確認してください。
>
> ここに危険な例があります：
> 	bool read_password = true;
>
> あなたがそれをどのように読んでいるか（意図していない）に応じて、2つの全く異なる解釈があります：
>
> - パスワードを読む必要があります
> - パスワードはすでに読み込まれています
>
> この場合、「読み込み」という単語を避け、need_passwordまたはuser_is_authenticatedという名前を付けてください。"
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def mobile
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
  end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  def markdown(text)
    render_options = {
        filter_html: false,
        hard_wrap: true
    }
    renderer = Redcarpet::Render::HTML.new(render_options)

    extensions = {
        autolink: true,
        fenced_code_blocks: true,
        lax_spacing: true,
        no_intra_emphasis: true,
        strikethrough: true,
        superscript: true,
        tables: true,
    }
    Redcarpet::Markdown.new(renderer, extensions).render(text).html_safe
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/views/layouts/_footer.html.erb
<footer><!-- 页脚 -->
    <div class="level-item has-text-centered">
        Vergil &copy 2018 
    </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar is-dark">
  <div class="navbar-brand">
    <a class="navbar-item" href="#">
      <%= image_tag 'icon.png' %>
    </a>
    <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>

  <div id="navbarExampleTransparentExample" class="navbar-menu">
    <div class="navbar-end">
        <%= link_to '主页', root_path, class: "navbar-item" %>
        <%= link_to '博客', blogs_index_path, class: "navbar-item" %>
        <%= link_to '摄影', photos_index_path, class: "navbar-item" %>
        <%= link_to '设计', portfolio_index_path, class: "navbar-item" %>
        <%= link_to '关于', about_index_path, class: "navbar-item" %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    
    <%= yield %>

    <%= render 'layouts/footer' %>
    
  </body>
</html>